In [1]:
#Labeling encoding
from sklearn.preprocessing import LabelEncoder

In [2]:
label_test = ['god', 'angel', "demon", "satan", "angel", "god"]

le_ = LabelEncoder()
le_.fit(label_test)

output = le_.transform(label_test)
print(output)

inverse = le_.inverse_transform(output)
print(inverse)

[2 0 1 3 0 2]
['god' 'angel' 'demon' 'satan' 'angel' 'god']


In [3]:
label_test = ['god', 'angel', "demon", "satan", "angel", "god"]

le_ = LabelEncoder()
output = le_.fit_transform(label_test)
print(output)
inverse = le_.inverse_transform(output)
print(inverse)

[2 0 1 3 0 2]
['god' 'angel' 'demon' 'satan' 'angel' 'god']


In [4]:
# simulate
import numpy as np
class labelEncoder:
  def __init__(self):
    self.label_to_int = {}
    self.int_to_label = {}
    
  def fit(self, labels) -> None:
    unique_labels = np.unique(np.array(labels))
    self.label_to_int = {key:item for key,item in enumerate(unique_labels)}  
    self.int_to_label = {item:key for key,item in self.label_to_int.items()} 
  
  def transform(self, labels):
    return np.array([self.int_to_label[label] for label in labels])
    
  def inverse(self, labels):
    return np.array([self.label_to_int[label] for label in labels])
  
test = labelEncoder()
test.fit(label_test)


test.transform(label_test)

array([2, 0, 1, 3, 0, 2])

In [5]:
from sklearn.preprocessing import StandardScaler

data = np.array([[1,2,3],[2,3,4],[3,4,5],[4,5,6]])
scaler = StandardScaler()
normalized = scaler.fit_transform(data)
print(normalized)

denormalized = scaler.inverse_transform(normalized)
print(denormalized)

[[-1.34164079 -1.34164079 -1.34164079]
 [-0.4472136  -0.4472136  -0.4472136 ]
 [ 0.4472136   0.4472136   0.4472136 ]
 [ 1.34164079  1.34164079  1.34164079]]
[[1. 2. 3.]
 [2. 3. 4.]
 [3. 4. 5.]
 [4. 5. 6.]]


In [6]:
class standardScaler:
  def __init__(self):
    self.mean = None
    self.sd = None
  
  def fit(self, data):
    self.mean = np.mean(data)
    self.sd = np.std(data)
    
  def transform(self, data):
    return (data-self.mean)/self.sd
  
  def inverse(self, data):
    return (data*self.sd)+self.mean
    
scaler = standardScaler()
scaler.fit(data)
print(scaler.mean)
print(scaler.sd)
    
normalized = scaler.transform(data)
print(normalized) 

denormalized = scaler.inverse(normalized)
print(denormalized) 


# #################################
train = data
test = [[4,3,2], [3,2,1]]
output = scaler.transform(test)
print(output)


3.5
1.3844373104863459
[[-1.8057878  -1.08347268 -0.36115756]
 [-1.08347268 -0.36115756  0.36115756]
 [-0.36115756  0.36115756  1.08347268]
 [ 0.36115756  1.08347268  1.8057878 ]]
[[1. 2. 3.]
 [2. 3. 4.]
 [3. 4. 5.]
 [4. 5. 6.]]
[[ 0.36115756 -0.36115756 -1.08347268]
 [-0.36115756 -1.08347268 -1.8057878 ]]


In [7]:
from sklearn.preprocessing import MinMaxScaler
print(data)

L,U = 0,1
Mx = MinMaxScaler(feature_range=(L,U))
Mx.fit(data)

scaled = Mx.transform(data)
print(scaled)

descaled = Mx.inverse_transform(scaled)
print(descaled)


[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]]
[[0.         0.         0.        ]
 [0.33333333 0.33333333 0.33333333]
 [0.66666667 0.66666667 0.66666667]
 [1.         1.         1.        ]]
[[1. 2. 3.]
 [2. 3. 4.]
 [3. 4. 5.]
 [4. 5. 6.]]


In [9]:
class Mxscaler:
  def __init__(self, L=0,U=1):
    self.L = L
    self.U = U
    self.min_v = None
    self.max_v = None
    
  def fit(self, data):
    self.min_v = np.min(data, axis=0)
    self.max_v = np.max(data, axis=0)
    
  def transform(self, data):
    temp = (data-self.min_v)/(self.max_v-self.min_v)
    return self.L+(temp*(self.U-self.L))
  
  def inverse(self, data):
    # A= (data-self.L)/(self.U-self.L)
    # B= A*(self.max_v-self.min_v)
    # return B+self.min_v
  
    A = (data - self.L) / (self.U - self.L)
    B = A * (self.max_v - self.min_v)
    return B + self.min_v
  
print(data)
  
Mx = Mxscaler()
Mx.fit(data)

scaled = Mx.transform(data)
print(scaled)

descaled = Mx.inverse(scaled)
print(descaled)

[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]]
[[0.         0.         0.        ]
 [0.33333333 0.33333333 0.33333333]
 [0.66666667 0.66666667 0.66666667]
 [1.         1.         1.        ]]
[[1. 2. 3.]
 [2. 3. 4.]
 [3. 4. 5.]
 [4. 5. 6.]]
