In [2]:
import numpy as np

#McCulloch-Pitts

## dataset

In [3]:
X = np.array([
        [0, 0, 0],
        [0, 0, 1],
        [0, 1, 0],
        [0, 1, 1],
        [1, 0, 0],
        [1, 0, 1],
        [1, 1, 0],
        [1, 1, 1]])
y_true = np.array([0, 0, 0, 1, 0, 0, 1, 1])

### Case 1

In [4]:
# Example
W1, W2, W3 = 0.125,0.625,0.125
threshold = 0.7

# X[:,0].dot(W1) + X[:,1].dot(W2) + X[:,2].dot(W3)

((X[:,0]*W1 + X[:,1]*W2 + X[:,2]*W3) >= threshold).astype(int)



array([0, 0, 0, 1, 0, 0, 1, 1])

### Case 2

In [5]:
# Code
W = np.array([0.125,0.625,0.125])
threshold = 0.7

((X.dot(W)) >= threshold).astype(int)


array([0, 0, 0, 1, 0, 0, 1, 1])

### Case 3

In [6]:
# CODE
class McCulloch_Pitts:
    def __init__(self, W = np.array([0.125,0.625,0.125])):
        self.threshold = 0.7
        self.W = W
        
    def fit(self, X, y):
        pass
        
    def predict(self, X):
        return ((X.dot(W)) >= threshold).astype(int)




test = McCulloch_Pitts()
test.predict(X)


array([0, 0, 0, 1, 0, 0, 1, 1])

# Perceptron

## dataset

In [37]:
X = np.array([
        [ 1, -1, -1, -1],
        [ 1, -1, -1,  1],
        [ 1, -1,  1, -1],
        [ 1, -1,  1,  1],
        [ 1,  1, -1, -1],
        [ 1,  1, -1,  1],
        [ 1,  1,  1, -1],
        [ 1,  1,  1,  1]])
y_true = np.array([-1,  1,  1,  1, -1,  1,  1,  1])

### Case 1

In [38]:
# CODE
n_iter = 1
eta = 0.1
W0, W1, W2, W3 = 0.2, -0.2, 0.2, 0.2

for _ in range(n_iter):
    for x, y in zip(X,y_true):
        y_hat = 1 if x[0]*W0+x[1]*W1+x[2]*W2+x[3]*W3 >= 0 else -1
        W0 = W0+(eta*(y-y_hat))*x[0]
        W1 = W1+(eta*(y-y_hat))*x[1]
        W2 = W2+(eta*(y-y_hat))*x[2]
        W3 = W3+(eta*(y-y_hat))*x[3]


y_pred = np.array([1 if x[0]*W0+x[1]*W1+x[2]*W2+x[3]*W3 >= 0 else -1 for x in X])
print(f"Output: {y_pred}")

Output: [-1  1  1  1 -1  1  1  1]


### Case 2

In [39]:
n_iter = 1
eta = 0.1
W = np.array([0.2, -0.2, 0.2, 0.2])

for _ in range(n_iter):
    for x, y in zip(X,y_true):
        y_hat = 1 if x.dot(W) >= 0 else -1
        W = W + eta*(y-y_hat)*x

y_pred = np.array([1 if x.dot(W) >= 0 else -1 for x in X])
print(f"Output: {y_pred}")

Output: [-1  1  1  1 -1  1  1  1]


### Case 3

In [40]:
# CODE
class Perceptron:
    def __init__(self, 
                 n_iter = 1, 
                 eta = 0.1, 
                 W = np.array([0.2, -0.2, 0.2, 0.2])
                 ):
        
        self.n_iter = n_iter
        self.eta = eta
        self.W = W
        
    def fit(self, X, y):
        for _ in range(self.n_iter):
            for x, y in zip(X,y_true):
                y_hat = 1 if x.dot(self.W) >= 0 else -1
                self.W = self.W + self.eta*(y-y_hat)*x
                
    def predict(self, X):
        return np.array([1 if x.dot(self.W) >= 0 else -1 for x in X])

test = Perceptron()
test.fit(X,y_true)
test.predict(X)

array([-1,  1,  1,  1, -1,  1,  1,  1])

# ADALINE

## Dataset

In [41]:
X = np.array([
        [ 1, -1, -1, -1],
        [ 1, -1, -1,  1],
        [ 1, -1,  1, -1],
        [ 1, -1,  1,  1],
        [ 1,  1, -1, -1],
        [ 1,  1, -1,  1],
        [ 1,  1,  1, -1],
        [ 1,  1,  1,  1]])
y_true = np.array([-1,  1,  1,  1, -1,  1,  1,  1])

### Case 1

In [49]:
n_iter = 1
eta = 0.1
W0, W1, W2, W3 = 0., 0., 0., 0.
for _ in range(n_iter):
    for x, y in zip(X,y_true):
        u = x[0]*W0+x[1]*W1+x[2]*W2+x[3]*W3
        W0 = W0-(eta*2*(u-y))*x[0]
        W1 = W1-(eta*2*(u-y))*x[1]
        W2 = W2-(eta*2*(u-y))*x[2]
        W3 = W3-(eta*2*(u-y))*x[3]

y_pred = np.array([1 if x[0]*W0+x[1]*W1+x[2]*W2+x[3]*W3 >= 0 else -1 for x in X])
print(f"Output: {y_pred}")

Output: [1 1 1 1 1 1 1 1]


### Case 2

In [50]:
n_iter = 1
eta = 0.1
W = np.array([0., 0., 0., 0.])

for _ in range(n_iter):
    for x, y in zip(X,y_true):
        u = x.dot(W)
        W = W-(eta*2*(u-y))*x

y_pred = np.array([1 if x.dot(W) >= 0 else -1 for x in X])
print(f"Output: {y_pred}")

Output: [1 1 1 1 1 1 1 1]


### Case 3

In [51]:
# CODE
class ADALINE:
    def __init__(self, 
                 n_iter = 1, 
                 eta = 0.1, 
                 W = np.array([0.2, -0.2, 0.2, 0.2])
                 ):
        
        self.n_iter = n_iter
        self.eta = eta
        self.W = W
        
    def fit(self, X, y):
        for _ in range(self.n_iter):
            for x, y in zip(X,y_true):
                u = x.dot(self.W)
                self.W = self.W-(self.eta*2*(u-y))*x
                
    def predict(self, X):
        return np.array([1 if x.dot(self.W) >= 0 else -1 for x in X])
    
test = ADALINE()
test.fit(X,y_true)
test.predict(X)


array([1, 1, 1, 1, 1, 1, 1, 1])