In [21]:
import numpy as np

In [22]:
X = np.array([[0.1, 0.2],
              [0.2, 0.4],
              [0.3, 0.1],
              [0.8, 0.5]])

U = np.array([[0.5, 0.5],
              [0.4, 0.6],
              [0.7, 0.3],
              [0.2, 0.8]])

In [4]:
A = U.T**2 @ X
A

array([[0.236, 0.183],
       [0.636, 0.523]])

In [20]:
B = (U.T**2).sum(axis=1, keepdims=True)
B

array([[0.94],
       [1.34]])

In [21]:
C = A/B
C

array([[0.25106383, 0.19468085],
       [0.47462687, 0.39029851]])

In [7]:
center0 = C[0]
center1 = C[1]

In [13]:
dist0 = np.linalg.norm(X-np.broadcast_to(center0, shape=(4,2)), axis=1)
dist1 = np.linalg.norm(X-np.broadcast_to(center1, shape=(4,2)), axis=1)


In [15]:
display(dist0)
display(dist1)

array([0.15115745, 0.21157379, 0.10657961, 0.62813271])

array([0.42018902, 0.27479817, 0.33877392, 0.34336874])