Import library ที่เกี่ยวข้อง

In [ ]:
import numpy as np
import pandas as pd

# Importing Flat File


ดาวน์โหลดไฟล์ universities.csv

https://drive.google.com/file/d/1NKvpBBRLLqbEDHVqD1SppJ-5Wjj4BQxl/view?usp=sharing

In [ ]:
!gdown 1NKvpBBRLLqbEDHVqD1SppJ-5Wjj4BQxl

Downloading...
From: https://drive.google.com/uc?id=1NKvpBBRLLqbEDHVqD1SppJ-5Wjj4BQxl
To: /content/universities.csv
100% 23.8k/23.8k [00:00<00:00, 32.7MB/s]


อ่านไฟล์ด้วย pandas

และแสดงตัวอย่างข้อมูล 10 แถวแรก

In [ ]:
data = pd.read_csv('universities.csv')
data.head(5)

UNIV_ID               UNIV_NAME         UNIV_TYPE_NAME  STR_CODE
0      100   จุฬาลงกรณ์มหาวิทยาลัย  มหาวิทยาลัยในกำกับรัฐ       100
1      200  มหาวิทยาลัยเกษตรศาสตร์  มหาวิทยาลัยในกำกับรัฐ       200
2      300      มหาวิทยาลัยขอนแก่น  มหาวิทยาลัยในกำกับรัฐ         0
3      400    มหาวิทยาลัยเชียงใหม่  มหาวิทยาลัยในกำกับรัฐ       400
4      500   มหาวิทยาลัยธรรมศาสตร์  มหาวิทยาลัยในกำกับรัฐ       500

อ่านไฟล์ พร้อมกำหนด index และเลือกมาเฉพาะ column UNIV_ID และ UNIV_NAME

In [ ]:
data = pd.read_csv('universities.csv', index_col='UNIV_ID', usecols=['UNIV_ID','UNIV_NAME'])
print(data.head(5))

                      UNIV_NAME
UNIV_ID                        
100       จุฬาลงกรณ์มหาวิทยาลัย
200      มหาวิทยาลัยเกษตรศาสตร์
300          มหาวิทยาลัยขอนแก่น
400        มหาวิทยาลัยเชียงใหม่
500       มหาวิทยาลัยธรรมศาสตร์


เรียงลำดับการแสดงผลของ column ใหม่

In [ ]:
data = pd.read_csv('universities.csv', usecols=['UNIV_ID','UNIV_NAME'])[['UNIV_NAME','UNIV_ID']]
print(data.head(5))

                UNIV_NAME  UNIV_ID
0   จุฬาลงกรณ์มหาวิทยาลัย      100
1  มหาวิทยาลัยเกษตรศาสตร์      200
2      มหาวิทยาลัยขอนแก่น      300
3    มหาวิทยาลัยเชียงใหม่      400
4   มหาวิทยาลัยธรรมศาสตร์      500


แสดงรายชื่อ columns ของ DataFrame

In [ ]:
data.columns

Index(['UNIV_NAME', 'UNIV_ID'], dtype='object')

แก้ไขชื่อ columns ของ DataFrame

In [ ]:
data = pd.read_csv('universities.csv', usecols=['UNIV_ID','UNIV_NAME'])
data.columns = ['id','name']
data.head(5)

id                    name
0  100   จุฬาลงกรณ์มหาวิทยาลัย
1  200  มหาวิทยาลัยเกษตรศาสตร์
2  300      มหาวิทยาลัยขอนแก่น
3  400    มหาวิทยาลัยเชียงใหม่
4  500   มหาวิทยาลัยธรรมศาสตร์

ปัญหาที่มักเจอเวลาอ่าน Flat Files

1. การระบุชนิดของข้อมูลของคอลัมน์ผิด

In [ ]:
data = pd.read_csv('universities.csv', usecols=['UNIV_ID','STR_CODE'])
data.head(5)

UNIV_ID  STR_CODE
0      100       100
1      200       200
2      300         0
3      400       400
4      500       500

ตรวจสอบชนิดของข้อมูลแต่ละคอลัมน์

In [ ]:
data.dtypes

UNIV_ID     int64
STR_CODE    int64
dtype: object

แก้ไขด้วยการกำหนดชนิดของข้อมูลของแต่ละคอลัมน์ใช้ parameter dtype

In [ ]:
data = pd.read_csv('universities.csv', dtype={'STR_CODE':str}, usecols=['UNIV_ID','STR_CODE'])
print(data.dtypes)
data.head(5)

UNIV_ID      int64
STR_CODE    object
dtype: object


UNIV_ID STR_CODE
0      100    00100
1      200    00200
2      300    00000
3      400    00400
4      500    00500

ปัญหาที่มักเจอเวลาอ่าน Flat Files

2. การระบุค่าของข้อมูลสูญหาย

In [ ]:
data = pd.read_csv('universities.csv', dtype={'STR_CODE':str}, usecols=['UNIV_ID','STR_CODE'])
print(data.dtypes)
data.head(5)

UNIV_ID      int64
STR_CODE    object
dtype: object


UNIV_ID STR_CODE
0      100    00100
1      200    00200
2      300    00000
3      400    00400
4      500    00500

ใช้ parameter na_values เพื่อจัดการข้อมูลที่อยู่ในรูปแบบที่กำหนดให้เป็น missing data

In [ ]:
data = pd.read_csv('universities.csv', dtype={'STR_CODE':str}, na_values={'STR_CODE':"00000"}, usecols=['UNIV_ID','STR_CODE'])
data.head(5)

UNIV_ID STR_CODE
0      100    00100
1      200    00200
2      300      NaN
3      400    00400
4      500    00500

ปัญหาที่มักเจอเวลาอ่าน Flat Files

3. Pandas ไม่สามารถอ่านข้อมูลได้

In [ ]:
!gdown 17taZfXThpa3PXQeIR4EANfkGnf2US06s

Downloading...
From: https://drive.google.com/uc?id=17taZfXThpa3PXQeIR4EANfkGnf2US06s
To: /content/universities-error.csv
100% 23.7k/23.7k [00:00<00:00, 49.0MB/s]


In [ ]:
data = pd.read_csv('universities-error.csv')
data.head(5)

ParserError: Error tokenizing data. C error: Expected 4 fields in line 4, saw 8


อ่านไฟล์แบบปกติ เพื่อตรวจสอบว่าเกิดข้อผิดพลาดที่บรรทัดใด

In [ ]:
err_file = open('universities-error.csv', 'r')
lines = err_file.readlines()
count = 0
for line in lines:
    count += 1
    if len(line.split(","))!=4:
      print("ERROR Line {}: {}".format(count, line.strip()))
      break
    else:
      print("Line {}: {}".format(count, line.strip()))

Line 1: UNIV_ID,UNIV_NAME,UNIV_TYPE_NAME,STR_CODE
Line 2: 100,จุฬาลงกรณ์มหาวิทยาลัย,มหาวิทยาลัยในกำกับรัฐ,00100
Line 3: 200,มหาวิทยาลัยเกษตรศาสตร์,มหาวิทยาลัยในกำกับรัฐ,00200
ERROR Line 4: 300,มหาวิทยาลัยขอนแก่น,00300,,,,,


ใช้ parameter **on_bad_lines='skip'** เพื่อข้าม record ที่ไม่สามารถ parse ได้

สามารถระบุค่าต่อไปนี้ได้

*   'error', จะแสดง Exception เมื่อเกิด error
*   'warn', จะแสดงข้อความแจ้งเตือน และข้ามข้อมูลบรรทัดที่เกิด error
*   'skip', จะข้ามข้อมูลบรรทัดที่เกิด error โดยไม่มีการแจ้งเตือนใด ๆ


In [ ]:
data = pd.read_csv('universities-error.csv', on_bad_lines='skip')
print(data.head(5))

   UNIV_ID               UNIV_NAME         UNIV_TYPE_NAME  STR_CODE
0      100   จุฬาลงกรณ์มหาวิทยาลัย  มหาวิทยาลัยในกำกับรัฐ       100
1      200  มหาวิทยาลัยเกษตรศาสตร์  มหาวิทยาลัยในกำกับรัฐ       200
2      400    มหาวิทยาลัยเชียงใหม่  มหาวิทยาลัยในกำกับรัฐ       400
3      500   มหาวิทยาลัยธรรมศาสตร์  มหาวิทยาลัยในกำกับรัฐ       500
4      600        มหาวิทยาลัยมหิดล  มหาวิทยาลัยในกำกับรัฐ       600


# Exporting Flat File

กำหนด DataFrame ที่จะ export

In [ ]:
num_uni_in_provice = {"กระบี่": 1, "กรุงเทพมหานคร":83, "กาญจนบุรี":4, "กาฬสินธุ์":2, "กำแพงเพชร":1, "ขอนแก่น":11, "จันทบุรี":4, "ฉะเชิงเทรา":2}
df = pd.DataFrame(num_uni_in_provice.items(), columns=["province", "num"])
df.set_index("province", inplace=True)
df

num
province          
กระบี่           1
กรุงเทพมหานคร   83
กาญจนบุรี        4
กาฬสินธุ์        2
กำแพงเพชร        1
ขอนแก่น         11
จันทบุรี         4
ฉะเชิงเทรา       2

ใช้ function to_csv ในการ export ข้อมูล

In [ ]:
df.to_csv('num_uni_in_provice.csv')

# Importing Spread Sheet

ดาวน์โหลดไฟล์ universities.xlsx

https://docs.google.com/spreadsheets/d/1NY3v2R7B-oo4C4ZvpPaKHYGBFVPWhL2C

In [ ]:
!gdown 1NY3v2R7B-oo4C4ZvpPaKHYGBFVPWhL2C

Downloading...
From: https://drive.google.com/uc?id=1NY3v2R7B-oo4C4ZvpPaKHYGBFVPWhL2C
To: /content/universities.xlsx
100% 18.9k/18.9k [00:00<00:00, 32.0MB/s]


อ่านไฟล์ด้วย pandas

และแสดงตัวอย่างข้อมูล 5 แถวแรก

In [ ]:
data = pd.read_excel('universities.xlsx', usecols=['UNIV_ID','UNIV_NAME'])
data.head(5)

UNIV_ID               UNIV_NAME
0      100   จุฬาลงกรณ์มหาวิทยาลัย
1      200  มหาวิทยาลัยเกษตรศาสตร์
2      300      มหาวิทยาลัยขอนแก่น
3      400    มหาวิทยาลัยเชียงใหม่
4      500   มหาวิทยาลัยธรรมศาสตร์

อ่านข้อมูลโดยกำหนดชนิดของข้อมูลให้กับคอลัมน์ STR_CODE

In [ ]:
data = pd.read_excel('universities.xlsx', dtype={'STR_CODE':str})
data.head(5)

UNIV_ID               UNIV_NAME         UNIV_TYPE_NAME STR_CODE
0      100   จุฬาลงกรณ์มหาวิทยาลัย  มหาวิทยาลัยในกำกับรัฐ    00100
1      200  มหาวิทยาลัยเกษตรศาสตร์  มหาวิทยาลัยในกำกับรัฐ    00200
2      300      มหาวิทยาลัยขอนแก่น  มหาวิทยาลัยในกำกับรัฐ    00300
3      400    มหาวิทยาลัยเชียงใหม่  มหาวิทยาลัยในกำกับรัฐ    00400
4      500   มหาวิทยาลัยธรรมศาสตร์  มหาวิทยาลัยในกำกับรัฐ    00500

ตรวจสอบจำนวนข้อมูลที่อ่านได้

In [ ]:
data.shape

(75, 4)

อ่านข้อมูลจาก sheet ที่ 2 ด้วยการใส่ชื่อ sheet

In [ ]:
data = pd.read_excel('universities.xlsx', dtype={'STR_CODE':str}, sheet_name=['Vocational'])
print("Type of 'data' is {}.".format(type(data)))
data

Type of 'data' is <class 'dict'>.


{'Vocational':    UNIV_ID                                UNIV_NAME  \
 0    19100       มหาวิทยาลัยเทคโนโลยีราชมงคลธัญบุรี   
 1    19200       มหาวิทยาลัยเทคโนโลยีราชมงคลกรุงเทพ   
 2    19300      มหาวิทยาลัยเทคโนโลยีราชมงคลตะวันออก   
 3    19400        มหาวิทยาลัยเทคโนโลยีราชมงคลพระนคร   
 4    19500  มหาวิทยาลัยเทคโนโลยีราชมงคลรัตนโกสินทร์   
 5    19600        มหาวิทยาลัยเทคโนโลยีราชมงคลล้านนา   
 6    19700      มหาวิทยาลัยเทคโนโลยีราชมงคลศรีวิชัย   
 7    19800    มหาวิทยาลัยเทคโนโลยีราชมงคลสุวรรณภูมิ   
 8    19900         มหาวิทยาลัยเทคโนโลยีราชมงคลอีสาน   
 
                 UNIV_TYPE_NAME STR_CODE  
 0  มหาวิทยาลัยเทคโนโลยีราชมงคล    19100  
 1  มหาวิทยาลัยเทคโนโลยีราชมงคล    19200  
 2  มหาวิทยาลัยเทคโนโลยีราชมงคล    19300  
 3  มหาวิทยาลัยเทคโนโลยีราชมงคล    19400  
 4  มหาวิทยาลัยเทคโนโลยีราชมงคล    19500  
 5  มหาวิทยาลัยเทคโนโลยีราชมงคล    19600  
 6  มหาวิทยาลัยเทคโนโลยีราชมงคล    19700  
 7  มหาวิทยาลัยเทคโนโลยีราชมงคล    19800  
 8  มหาวิทยาลัยเทคโนโลยีราชมงคล    19

การจะใช้งานต้อง extract เอาค่าออกมาจากตัวแปร dictionary

In [ ]:
data = data['Vocational']
data.head(5)

UNIV_ID                                UNIV_NAME  \
0    19100       มหาวิทยาลัยเทคโนโลยีราชมงคลธัญบุรี   
1    19200       มหาวิทยาลัยเทคโนโลยีราชมงคลกรุงเทพ   
2    19300      มหาวิทยาลัยเทคโนโลยีราชมงคลตะวันออก   
3    19400        มหาวิทยาลัยเทคโนโลยีราชมงคลพระนคร   
4    19500  มหาวิทยาลัยเทคโนโลยีราชมงคลรัตนโกสินทร์   

                UNIV_TYPE_NAME STR_CODE  
0  มหาวิทยาลัยเทคโนโลยีราชมงคล    19100  
1  มหาวิทยาลัยเทคโนโลยีราชมงคล    19200  
2  มหาวิทยาลัยเทคโนโลยีราชมงคล    19300  
3  มหาวิทยาลัยเทคโนโลยีราชมงคล    19400  
4  มหาวิทยาลัยเทคโนโลยีราชมงคล    19500

อ่านข้อมูลจาก sheet ที่ 3 ด้วยการใส่ index ของ sheet (index เริ่มต้นที่ 0)

In [ ]:
data = pd.read_excel('universities.xlsx', dtype={'STR_CODE':str}, sheet_name=2)
data.head(5)

UNIV_ID                  UNIV_NAME    UNIV_TYPE_NAME STR_CODE
0    10700    มหาวิทยาลัยวงษ์ชวลิตกุล  มหาวิทยาลัยเอกชน    10700
1    10000       มหาวิทยาลัยเจ้าพระยา  มหาวิทยาลัยเอกชน    10000
2    10100       มหาวิทยาลัยเมธารัถย์  มหาวิทยาลัยเอกชน    10100
3    10200       มหาวิทยาลัยเวสเทิร์น  มหาวิทยาลัยเอกชน    10200
4    10300  มหาวิทยาลัยธุรกิจบัณฑิตย์  มหาวิทยาลัยเอกชน    10300

การใช้ sheet_name=None จะทำให้ read_excel() อ่าน sheet ทั้งหมดใน workbook

In [ ]:
data = pd.read_excel('universities.xlsx', dtype={'STR_CODE':str}, sheet_name=None)
print("Type of 'data' is {}.".format(type(data)))

Type of 'data' is <class 'dict'>.


In [ ]:
for key, value in data.items():
  print("Sheet name = {}, Shape of records = {}".format(key,value.shape))

Sheet name = Government, Shape of records = (75, 4)
Sheet name = Vocational, Shape of records = (9, 4)
Sheet name = Private, Shape of records = (70, 4)
Sheet name = Other, Shape of records = (17, 4)


# Exporting Spread Sheet

จากข้อมูลที่เป็น DataFrame

In [ ]:
num_uni_in_provice = {"กระบี่": 1, "กรุงเทพมหานคร":83, "กาญจนบุรี":4, "กาฬสินธุ์":2, "กำแพงเพชร":1, "ขอนแก่น":11, "จันทบุรี":4, "ฉะเชิงเทรา":2}
df = pd.DataFrame(num_uni_in_provice.items(), columns=["province", "num"])
df.set_index("province", inplace=True)
df

num
province          
กระบี่           1
กรุงเทพมหานคร   83
กาญจนบุรี        4
กาฬสินธุ์        2
กำแพงเพชร        1
ขอนแก่น         11
จันทบุรี         4
ฉะเชิงเทรา       2

เรียกใช้ function to_excel

In [ ]:
df.to_excel("num_uni_in_provice.xlsx")

หรือระบุข้อมูลลงไปในแต่ละ sheet name

In [ ]:
df.to_excel("output_with_sheetname.xlsx", sheet_name='data_with_SheetName')

หากต้องการเขียนข้อมูลลงในหลาย work sheet ต้องใช้ ExcelWriter object เข้ามาช่วย

In [ ]:
num_uni_in_provice1 = {"กระบี่": 1, "กรุงเทพมหานคร":83, "กาญจนบุรี":4, "กาฬสินธุ์":2, "กำแพงเพชร":1}
df1 = pd.DataFrame(num_uni_in_provice1.items(), columns=["province", "num"])
df1.set_index("province", inplace=True)

num_uni_in_provice2 = {"ขอนแก่น":11, "จันทบุรี":4, "ฉะเชิงเทรา":2}
df2 = pd.DataFrame(num_uni_in_provice2.items(), columns=["province", "num"])
df2.set_index("province", inplace=True)
with pd.ExcelWriter('output_multiSheets.xlsx') as writer:
    df1.to_excel(writer, sheet_name='Province_1')
    df2.to_excel(writer, sheet_name='Province_2')

# Exporting Pickle File

import library ที่เกี่ยวข้อง

In [ ]:
import pickle

เปิดไฟล์สำหรับเขียนด้วยฟังก์ชัน open และใช้ mode เป็นการเขียนไฟล์ไบนารี (wb)

โหลดข้อมูลจากตัวแปรใส่ไฟล์ด้วย method dump() จาก library pickle

In [ ]:
population_dict = {'California': 38332521, 'Texas': 26448193,
                   'New York': 19651127, 'Florida': 19552860,
                   'Illinois': 12882135}
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
             'Florida': 170312, 'Illinois': 149995}
population = pd.Series(population_dict)
area = pd.Series(area_dict)
data = pd.DataFrame({'population': population, 'area': area})
density = pd.Series(data['population']/data['area'])

pkl_file = open('population.pkl', 'wb')
pickle.dump([data, density], pkl_file)
pkl_file.close()

# Importing Pickle File

เปิดไฟล์สำหรับอ่านด้วยฟังก์ชัน open และใช้ mode เป็นการอ่านไฟล์ไบนารี (rb)

อ่านข้อมูลใส่ตัวแปรด้วย method load() จาก library pickle

In [ ]:
pkl_file = open('population.pkl', 'rb')
data = pickle.load(pkl_file)
for idx in range(len(data)):
  print("index {} => \n{}".format(idx, data[idx]))

pkl_file.close()

index 0 => 
            population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995
index 1 => 
California     90.413926
Texas          38.018740
New York      139.076746
Florida       114.806121
Illinois       85.883763
dtype: float64


# Importing HDF5

Download HDF5 file 'temperature.hdf5'

https://drive.google.com/file/d/1NesF-rDMhj-2SrlAmWJR99WO3ZtMBkgE/view?usp=sharing

In [ ]:
!gdown 1NesF-rDMhj-2SrlAmWJR99WO3ZtMBkgE

Downloading...
From: https://drive.google.com/uc?id=1NesF-rDMhj-2SrlAmWJR99WO3ZtMBkgE
To: /content/temperature.hdf5
100% 716k/716k [00:00<00:00, 104MB/s]


In [ ]:
import h5py

เปิดไฟล์ HDF5 ด้วย h5py library

สำรวจ key (ทั้ง groups และ datasets) ด้วย method keys()

In [ ]:
data = h5py.File('temperature.hdf5', 'r')
print(data.keys())
print([i for i in data.items()])

<KeysViewHDF5 ['place_A', 'place_B']>
[('place_A', <HDF5 group "/place_A" (2 members)>), ('place_B', <HDF5 group "/place_B" (2 members)>)]


เข้าถึงข้อมูลผ่าน key ด้วย method get()

สำรวจสมาชิกในกลุ่มข้อมูลด้วย method items()

In [ ]:
place_A = data.get('place_A')
print(place_A.keys())
print(place_A.items())

<KeysViewHDF5 ['minutes', 'summary']>
ItemsViewHDF5(<HDF5 group "/place_A" (2 members)>)


ใช้ list comprehension ในการตรวจสอบข้อมูลใน group place_A

In [ ]:
print([i for i in place_A.items()])

[('minutes', <HDF5 dataset "minutes": shape (43200,), type "<f8">), ('summary', <HDF5 group "/place_A/summary" (3 members)>)]


ใช้ list comprehension ในการตรวจสอบ Attribute ของไฟล์ HDF5, groups, datasets ด้วย Attribute attrs

In [ ]:
print([i for i in data.attrs])
print([i for i in place_A.attrs])

['num_of_place', 'title']
['lat', 'long']


In [ ]:
print("This file contains data from {} places.".format(data.attrs['num_of_place']))
print("Title of this dataset: {}".format(data.attrs['title']))
print("Location of Place A at LAT {}, LONG {}".format(place_A.attrs['lat'],place_A.attrs['long']))

This file contains data from 2 places.
Title of this dataset: This file contains temperature of somewhere
Location of Place A at LAT 16.4322, LONG 102.8236


ใช้ method get() ในการเข้าถึงแบบลำดับชั้นได้

In [ ]:
place_A_summary = data.get('place_A/summary')
print([i for i in place_A_summary.items()])

[('days', <HDF5 dataset "days": shape (30,), type "<f8">), ('hours', <HDF5 dataset "hours": shape (720,), type "<f8">), ('weeks', <HDF5 dataset "weeks": shape (4,), type "<f8">)]


นำค่ามาใช้ด้วยการเข้าถึงผ่าน index

In [ ]:
avg_weeks = place_A_summary.get('weeks')
avg_weeks[()]

array([30.43459169, 30.49557515, 30.33939346, 30.55663503])

In [ ]:
avg_weeks[0]

30.434591689994775

หรือการแปลงค่าเป็น Numpy array

In [ ]:
np.array(avg_weeks)

array([30.43459169, 30.49557515, 30.33939346, 30.55663503])

# Exporting HDF5

สร้างไฟล์ใหม่ผ่าน library hdf5

In [ ]:
hf = h5py.File('test_creating.hdf5', 'w')

 กำหนด attribute

In [ ]:
hf.attrs['title'] = "For creating HDF5 file"

การสร้าง group ของข้อมูลด้วย method create_group()

In [ ]:
group1 = hf.create_group('group1')

การสร้าง dataset ของข้อมูลด้วย method create_dataset()

In [ ]:
test_data = np.random.randint(1,1000,size=(100,100))
dataset1 = group1.create_dataset('dataset1', data=test_data)

สิ้นสุดการเขียนไฟล์ด้วย method close()

In [ ]:
hf.close()

ตรวจสอบไฟล์ที่สร้าง

In [ ]:
data = h5py.File('test_creating.hdf5', 'r')
print(data.keys())
print([i for i in data.attrs])

<KeysViewHDF5 ['group1']>
['title']


In [ ]:
print(data.get('group1'))
print(data.get('group1').keys())
print("Title of this dataset: {}".format(data.attrs['title']))

<HDF5 group "/group1" (1 members)>
<KeysViewHDF5 ['dataset1']>
Title of this dataset: For creating HDF5 file


In [ ]:
print(np.array(data.get('group1/dataset1')))

[[236 332 269 ... 402 481  43]
 [893 808 687 ... 638 563 241]
 [850 180 431 ... 656 268 665]
 ...
 [ 20 802 916 ... 293 740 215]
 [763 492 669 ... 530 385 994]
 [929 663 880 ... 208 171 962]]
